version: "3.8"

networks:
    bluesky-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/24
                  gateway: 172.19.0.1

services:
    postgres_db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
        networks:
            - bluesky-network
        ports:
            - "6543:5432"
    bluesky:
        restart: always
        image: bluesky
        container_name: bluesky
        user: root
        env_file:
            - ../.env

        working_dir: /workspaces/bluesky

        networks:
            - bluesky-network
        ports:
            - "6969:6969"
        volumes:
            - type: bind
              source: ..
              target: /workspaces/bluesky
            - type: bind
              source: ../data/
              target: /workspaces/bluesky/data/
            - type: bind
              source: ../.env
              target: /workspaces/bluesky/.env
        command: ["sh", "-c", "make"]
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
            - "postgres_db"
